development:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432
  timeout: 5000



test:
  adapter: postgresql
  encoding: unicode
  database: test2
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432
  timeout: 5000
